"""
Tests for snapfix.plugin — the pytest plugin.

These tests verify plugin behaviour using pytest's own testing utilities.
"""
import os
import pathlib
import sys

import pytest


# ── Import surface ────────────────────────────────────────────────────────────

def test_plugin_imports():
    from snapfix.plugin import (
        pytest_addoption,
        pytest_configure,
        pytest_sessionstart,
        pytest_collection_modifyitems,
        pytest_collect_file,
        SnapfixFixtureFile,
        snapfix_store,
        snapfix_config,
    )
    assert callable(pytest_addoption)
    assert callable(pytest_configure)
    assert callable(pytest_collect_file)


def test_snapfix_fixture_file_is_pytest_module():
    from snapfix.plugin import SnapfixFixtureFile
    assert issubclass(SnapfixFixtureFile, pytest.Module)


# ── snapfix_store fixture ─────────────────────────────────────────────────────

def test_snapfix_store_fixture_returns_store(snapfix_store):
    from snapfix.store import SnapfixStore
    assert isinstance(snapfix_store, SnapfixStore)

def test_snapfix_store_fixture_output_dir_exists(snapfix_store):
    assert snapfix_store.output_dir.exists()

def test_snapfix_store_fixture_is_writable(snapfix_store):
    snapfix_store.write("plugin_test", "# test", {})
    assert snapfix_store.exists("plugin_test")


# ── snapfix_config fixture ────────────────────────────────────────────────────

def test_snapfix_config_fixture_returns_config(snapfix_config):
    from snapfix.config import SnapfixConfig
    assert isinstance(snapfix_config, SnapfixConfig)

def test_snapfix_config_fixture_is_enabled(snapfix_config):
    assert snapfix_config.enabled is True

def test_snapfix_config_fixture_has_output_dir(snapfix_config):
    assert snapfix_config.output_dir.exists()


# ── Plugin file detection ─────────────────────────────────────────────────────

def test_plugin_ignores_non_snapfix_files(tmp_path):
    """pytest_collect_file should return None for non-snapfix files."""
    from snapfix.plugin import pytest_collect_file

    regular = tmp_path / "test_something.py"
    regular.write_text("def test_x(): pass")
    # We cannot easily call pytest_collect_file without a real pytest session,
    # but we can verify the header check logic
    from snapfix.plugin import _read_header
    header = _read_header(regular)
    assert "Generated by snapfix" not in header


def test_read_header_snapfix_file(tmp_path):
    """_read_header correctly identifies generated fixture files."""
    from snapfix.plugin import _read_header
    fx = tmp_path / "snapfix_invoice.py"
    fx.write_text("# Generated by snapfix — do not edit manually\nimport pytest\n")
    header = _read_header(fx)
    assert "Generated by snapfix" in header


def test_read_header_missing_file(tmp_path):
    """_read_header returns empty string for missing files."""
    from snapfix.plugin import _read_header
    result = _read_header(tmp_path / "nonexistent.py")
    assert result == ""


# ── Environment variable control ─────────────────────────────────────────────

def test_env_vars_control_capture(tmp_path, monkeypatch):
    """SNAPFIX_ENABLED=false disables capture even with the plugin loaded."""
    import sys
    monkeypatch.setenv("SNAPFIX_OUTPUT_DIR", str(tmp_path))
    monkeypatch.setenv("SNAPFIX_ENABLED",    "false")

    for m in list(sys.modules):
        if "snapfix" in m and m not in ("snapfix.plugin",):
            sys.modules.pop(m, None)

    from snapfix import capture

    @capture("plugin_env_test")
    def fn():
        return {"x": 1}

    fn()
    assert not list(tmp_path.glob("snapfix_*.py"))


def test_capture_enabled_via_env(tmp_path, monkeypatch):
    """SNAPFIX_ENABLED=true enables capture."""
    import sys
    monkeypatch.setenv("SNAPFIX_OUTPUT_DIR", str(tmp_path))
    monkeypatch.setenv("SNAPFIX_ENABLED",    "true")

    for m in list(sys.modules):
        if "snapfix" in m and m not in ("snapfix.plugin",):
            sys.modules.pop(m, None)

    from snapfix import capture

    @capture("plugin_enabled_test")
    def fn():
        return {"y": 2}

    fn()
    assert any(tmp_path.glob("snapfix_*.py"))
