from __future__ import annotations

import ast
import datetime
import re
import textwrap
from typing import Any

_FIXTURE_HEADER = (
    "# Generated by snapfix -- do not edit manually\n"
    "# Regenerate: re-run the @snapfix.capture decorated function\n"
    "# Captured : {captured_at}\n"
    "# Scrubbed : {scrubbed_fields}\n"
    "import pytest\n"
    "from snapfix import reconstruct\n"
    "\n"
)


def _to_literal(obj: Any, indent: int = 2) -> str:
    """Render a JSON-serialisable object as a pretty-printed Python literal."""
    ind = " " * indent
    if obj is None:
        return "None"
    if isinstance(obj, bool):
        return "True" if obj else "False"
    if isinstance(obj, (int, float, str)):
        return repr(obj)
    if isinstance(obj, list):
        if not obj:
            return "[]"
        items = ",\n".join(ind + "    " + _to_literal(x, indent + 4) for x in obj)
        return "[\n" + items + ",\n" + ind + "]"
    if isinstance(obj, dict):
        if not obj:
            return "{}"
        parts = []
        for k, v in obj.items():
            parts.append(ind + "    " + repr(k) + ": " + _to_literal(v, indent + 4))
        return "{\n" + ",\n".join(parts) + ",\n" + ind + "}"
    return repr(obj)


class SnapfixCodegen:
    def generate(
        self,
        name: str,
        data: Any,
        scrubbed_fields: list[str],
        captured_at: datetime.datetime,
    ) -> str:
        fn_name = _sanitize(name)
        header = _FIXTURE_HEADER.format(
            captured_at=captured_at.isoformat(),
            scrubbed_fields=", ".join(scrubbed_fields) or "none",
        )
        body = _to_literal(data)
        source = (
            header
            + "@pytest.fixture\n"
            + f"def {fn_name}():\n"
            + "    return reconstruct(\n"
            + textwrap.indent(body, "        ")
            + "\n    )\n"
        )
        try:
            ast.parse(source)
        except SyntaxError as e:
            raise ValueError(f"Generated invalid Python source: {e}") from e
        return source


def _sanitize(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s or "_unnamed"
