from __future__ import annotations

import ast
import datetime
import inspect
import re
import textwrap
from typing import Any, Callable, List, Optional

from snapfix.serializer import _MARKER, _UNSZ, _CIRC, _TRUNC, _DEPTH

_TYPE_LABELS: dict[str, str] = {
    "datetime":  "datetime",
    "date":      "date",
    "time":      "time",
    "timedelta": "timedelta",
    "uuid":      "UUID",
    "decimal":   "Decimal",
    "bytes":     "bytes",
    "bytearray": "bytearray",
    "path":      "Path",
    "enum":      "Enum value",
    "tuple":     "tuple → list",
    "set":       "set",
    "frozenset": "frozenset",
    "float":     "float (nan/inf)",
}

_FIXTURE_HEADER = (
    "# Generated by snapfix — do not edit manually\n"
    "# Regenerate  : re-run the @snapfix.capture decorated function\n"
    "# Captured    : {captured_at}\n"
    "# Source      : {source}\n"
    "# Scrubbed    : {scrubbed_fields}\n"
    "#\n"
    "# ⚠  Review before committing: value-level PII is not detected.\n"
    "#    All scrubbed fields are listed above.\n"
    "import pytest\n"
    "from snapfix import reconstruct\n"
    "\n"
)

_MARKER_KEYS = frozenset([_MARKER, _UNSZ, _CIRC, _TRUNC, _DEPTH])


def _type_comment(obj: Any) -> str:
    """Return a trailing comment for a type-marked dict, or ''."""
    if not isinstance(obj, dict):
        return ""
    marker = obj.get(_MARKER)
    if marker and marker in _TYPE_LABELS:
        return f"  # {_TYPE_LABELS[marker]}"
    if _UNSZ in obj:
        return f"  # unserializable: {obj.get('__snapfix_type_name__', '?')}"
    if _CIRC in obj:
        return "  # circular reference"
    if _TRUNC in obj:
        return "  # truncated: exceeded max_size_bytes"
    if _DEPTH in obj:
        return "  # truncated: exceeded max_depth"
    return ""


def _is_marker_dict(obj: Any) -> bool:
    """True if this dict is a snapfix type/sentinel marker dict."""
    return isinstance(obj, dict) and bool(set(obj) & _MARKER_KEYS)


def _to_literal(obj: Any, indent: int = 2) -> str:
    """
    Render a JSON-serialisable object as a pretty-printed Python literal.

    Inline comments (# datetime, # Decimal, etc.) are placed on the same
    line as the key–value pair, AFTER the trailing comma, by embedding the
    comma directly in each entry rather than using ','.join().

    Type-marker dicts are always rendered on a single line so the comment
    never splits across a multi-line closing brace.
    """
    ind = " " * indent

    if obj is None:
        return "None"
    if isinstance(obj, bool):
        return "True" if obj else "False"
    if isinstance(obj, (int, float, str)):
        return repr(obj)

    if isinstance(obj, list):
        if not obj:
            return "[]"
        lines = []
        for x in obj:
            comment  = _type_comment(x)
            x_lit    = _to_literal(x, indent + 4)
            # Comma is embedded; comment follows the comma
            lines.append(ind + "    " + x_lit + "," + comment)
        return "[\n" + "\n".join(lines) + "\n" + ind + "]"

    if isinstance(obj, dict):
        if not obj:
            return "{}"

        # Marker dicts: always single-line (2–3 small keys; no nested structure)
        if _is_marker_dict(obj):
            inner = ", ".join(repr(k) + ": " + repr(v) for k, v in obj.items())
            return "{" + inner + "}"

        # Regular dicts: multi-line with embedded commas
        lines = []
        for k, v in obj.items():
            v_lit    = _to_literal(v, indent + 4)
            comment  = _type_comment(v)
            # Always embed the comma; comment (if any) comes after the comma
            lines.append(ind + "    " + repr(k) + ": " + v_lit + "," + comment)
        return "{\n" + "\n".join(lines) + "\n" + ind + "}"

    return repr(obj)


class SnapfixCodegen:
    def generate(
        self,
        name: str,
        data: Any,
        scrubbed_fields: List[str],
        captured_at: datetime.datetime,
        source_fn: Optional[Callable] = None,
    ) -> str:
        fn_name = _sanitize(name)

        if source_fn is not None:
            try:
                module   = getattr(source_fn, "__module__", "?")
                qualname = getattr(source_fn, "__qualname__", "?")
                try:
                    file_path  = inspect.getfile(source_fn)
                    source_ref = f"{module}.{qualname} ({file_path})"
                except (TypeError, OSError):
                    source_ref = f"{module}.{qualname}"
            except Exception:
                source_ref = "unknown"
        else:
            source_ref = "unknown"

        header = _FIXTURE_HEADER.format(
            captured_at=captured_at.isoformat(timespec="seconds"),
            source=source_ref,
            scrubbed_fields=", ".join(scrubbed_fields) if scrubbed_fields else "none",
        )

        body   = _to_literal(data)
        source = (
            header
            + "@pytest.fixture\n"
            + f"def {fn_name}():\n"
            + "    return reconstruct(\n"
            + textwrap.indent(body, "        ")
            + "\n    )\n"
        )

        try:
            ast.parse(source)
        except SyntaxError as e:
            raise ValueError(f"Generated invalid Python source: {e}") from e
        return source


def _sanitize(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if s and s[0].isdigit():
        s = "_" + s
    return s or "_unnamed"
