"""
snapfix pytest plugin.

Registers snapfix as a first-class pytest plugin so that:

  1. Generated fixtures appear in `pytest --fixtures`
  2. `--snapfix-capture` / `--no-snapfix-capture` flags control capture globally
  3. `--snapfix-dir` sets the output directory for the session
  4. Captured fixture files are auto-discovered and registered

To use as a conftest plugin (without installing as an entry point):

    # conftest.py
    pytest_plugins = ["snapfix.plugin"]

Or install snapfix normally — the entry point in pyproject.toml registers
it automatically with every pytest run.
"""
from __future__ import annotations

import os
import pathlib
from typing import Optional

import pytest


# ── pytest hooks ──────────────────────────────────────────────────────────────

def pytest_addoption(parser: pytest.Parser) -> None:
    group = parser.getgroup("snapfix", "snapfix fixture capture")
    group.addoption(
        "--snapfix-capture",
        action="store_true",
        default=False,
        dest="snapfix_capture",
        help="Enable snapfix capture for this test session (sets SNAPFIX_ENABLED=true).",
    )
    group.addoption(
        "--no-snapfix-capture",
        action="store_true",
        default=False,
        dest="snapfix_no_capture",
        help="Disable snapfix capture for this test session (sets SNAPFIX_ENABLED=false).",
    )
    group.addoption(
        "--snapfix-dir",
        action="store",
        default=None,
        dest="snapfix_dir",
        metavar="PATH",
        help="Override snapfix fixture output directory for this session.",
    )


def pytest_configure(config: pytest.Config) -> None:
    """Apply CLI flags to the environment before any tests run."""
    if config.option.snapfix_capture:
        os.environ["SNAPFIX_ENABLED"] = "true"
    if config.option.snapfix_no_capture:
        os.environ["SNAPFIX_ENABLED"] = "false"
    if config.option.snapfix_dir:
        os.environ["SNAPFIX_OUTPUT_DIR"] = config.option.snapfix_dir

    # Register our marker so pytest --markers shows it
    config.addinivalue_line(
        "markers",
        "snapfix_capture(name): mark test to enable snapfix capture for a specific fixture name",
    )


def pytest_sessionstart(session: pytest.Session) -> None:
    """Print a one-line status message when snapfix capture is active."""
    enabled = os.environ.get("SNAPFIX_ENABLED", "").lower()
    if enabled == "true":
        output_dir = os.environ.get("SNAPFIX_OUTPUT_DIR", "tests/fixtures")
        session.config.pluginmanager.get_plugin("terminalreporter")
        # Use warnings channel to avoid polluting output
        import warnings
        warnings.warn(
            f"snapfix: capture ENABLED — fixtures will be written to '{output_dir}'",
            stacklevel=1,
        )


def pytest_collection_modifyitems(
    session: pytest.Session,
    config: pytest.Config,
    items: list,
) -> None:
    """Auto-skip snapfix capture in CI unless explicitly enabled."""
    # If running in CI and capture was not explicitly requested, disable it
    in_ci      = os.environ.get("CI", "").lower() in ("true", "1", "yes")
    enabled    = os.environ.get("SNAPFIX_ENABLED", "").lower()
    explicitly = config.option.snapfix_capture

    if in_ci and enabled != "true" and not explicitly:
        os.environ["SNAPFIX_ENABLED"] = "false"


# ── Fixture auto-discovery ─────────────────────────────────────────────────────

def pytest_collect_file(
    parent: pytest.Collector,
    file_path: pathlib.Path,
) -> Optional[pytest.Collector]:
    """
    Auto-collect snapfix_*.py fixture files from the configured output directory.

    This allows 'pytest --collect-only' to show snapfix fixtures, and makes
    them available to all tests without explicit imports.
    """
    # Only handle files that look like snapfix-generated fixtures
    if (
        file_path.name.startswith("snapfix_")
        and file_path.suffix == ".py"
        and "# Generated by snapfix" in _read_header(file_path)
    ):
        return SnapfixFixtureFile.from_parent(parent, path=file_path)
    return None


def _read_header(path: pathlib.Path, lines: int = 3) -> str:
    """Read the first few lines of a file without loading the whole thing."""
    try:
        with path.open() as f:
            return "".join(f.readline() for _ in range(lines))
    except Exception:
        return ""


class SnapfixFixtureFile(pytest.Module):
    """
    pytest.Module subclass that wraps a snapfix-generated fixture file.

    Appears in `pytest --collect-only` and `pytest --fixtures` output with
    a label indicating it was generated by snapfix.
    """
    def collect(self):
        # Delegate to the standard Module collector
        yield from super().collect()


# ── Fixture for the snapfix store (useful in tests that test snapfix itself) ──

@pytest.fixture(scope="session")
def snapfix_store(tmp_path_factory):
    """
    A session-scoped SnapfixStore backed by a temporary directory.
    Useful for testing code that interacts with the snapfix store directly.
    """
    from snapfix.store import SnapfixStore
    return SnapfixStore(tmp_path_factory.mktemp("snapfix_store"))


@pytest.fixture(scope="session")
def snapfix_config(tmp_path_factory):
    """
    A session-scoped SnapfixConfig pointing to a temporary output directory.
    Useful for testing code that uses @capture.
    """
    from snapfix.config import SnapfixConfig
    return SnapfixConfig(
        output_dir=tmp_path_factory.mktemp("snapfix_fixtures"),
        enabled=True,
    )
